// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.5
// source: game.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JoinRequest is sent once by the client upon connecting to enter the game arena.
type JoinRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique player identifier assigned by the gateway session or authenticated user token.
	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	// Human-readable display name chosen by the player.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *JoinRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// UserCmd represents a single client input frame captured at input sampling frequency.
// Used by the server to simulate physics and by the client for prediction reconciliation.
type UserCmd struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique player identifier sending this input command (verified/injected by gateway).
	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	// Monotonically increasing sequence number for this player's commands (used for ack reconciliation).
	Seq int32 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// Client-side timestamp in milliseconds when input was sampled.
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Normalized X movement direction (-1.0 for left, 0.0 for none, 1.0 for right).
	Dx float32 `protobuf:"fixed32,4,opt,name=dx,proto3" json:"dx,omitempty"`
	// Normalized Y movement direction (-1.0 for up, 0.0 for none, 1.0 for down).
	Dy float32 `protobuf:"fixed32,5,opt,name=dy,proto3" json:"dy,omitempty"`
	// Aim direction in radians (angle between player origin and mouse cursor).
	AimAngle float32 `protobuf:"fixed32,6,opt,name=aim_angle,json=aimAngle,proto3" json:"aim_angle,omitempty"`
	// Flag indicating whether the primary weapon fire action was triggered during this command.
	Fire          bool `protobuf:"varint,7,opt,name=fire,proto3" json:"fire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCmd) Reset() {
	*x = UserCmd{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCmd) ProtoMessage() {}

func (x *UserCmd) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCmd.ProtoReflect.Descriptor instead.
func (*UserCmd) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *UserCmd) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *UserCmd) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *UserCmd) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *UserCmd) GetDx() float32 {
	if x != nil {
		return x.Dx
	}
	return 0
}

func (x *UserCmd) GetDy() float32 {
	if x != nil {
		return x.Dy
	}
	return 0
}

func (x *UserCmd) GetAimAngle() float32 {
	if x != nil {
		return x.AimAngle
	}
	return 0
}

func (x *UserCmd) GetFire() bool {
	if x != nil {
		return x.Fire
	}
	return false
}

// LeaveRequest is sent when a player gracefully disconnects from the game session.
type LeaveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique player identifier of the departing player.
	PlayerId      string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

// JoinResponse is sent by the server to acknowledge JoinRequest and provide initial spawn parameters.
type JoinResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the player was successfully admitted to the match, false if rejected.
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// Initial spawn position X coordinate in arena pixels.
	SpawnX float32 `protobuf:"fixed32,2,opt,name=spawn_x,json=spawnX,proto3" json:"spawn_x,omitempty"`
	// Initial spawn position Y coordinate in arena pixels.
	SpawnY        float32 `protobuf:"fixed32,3,opt,name=spawn_y,json=spawnY,proto3" json:"spawn_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *JoinResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *JoinResponse) GetSpawnX() float32 {
	if x != nil {
		return x.SpawnX
	}
	return 0
}

func (x *JoinResponse) GetSpawnY() float32 {
	if x != nil {
		return x.SpawnY
	}
	return 0
}

// EntityState represents the authoritative state of a single player character in the arena.
type EntityState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the entity (matches player_id for players).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Authoritative X position coordinate in arena pixels.
	X float32 `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	// Authoritative Y position coordinate in arena pixels.
	Y float32 `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	// Current facing/aim direction in radians.
	Angle float32 `protobuf:"fixed32,4,opt,name=angle,proto3" json:"angle,omitempty"`
	// Current health points (0 represents eliminated state).
	Health int32 `protobuf:"varint,5,opt,name=health,proto3" json:"health,omitempty"`
	// True if this entity represents the receiving client's own avatar (used for prediction reconciliation).
	IsSelf        bool `protobuf:"varint,6,opt,name=is_self,json=isSelf,proto3" json:"is_self,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityState) Reset() {
	*x = EntityState{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityState) ProtoMessage() {}

func (x *EntityState) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityState.ProtoReflect.Descriptor instead.
func (*EntityState) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *EntityState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityState) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *EntityState) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *EntityState) GetAngle() float32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

func (x *EntityState) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *EntityState) GetIsSelf() bool {
	if x != nil {
		return x.IsSelf
	}
	return false
}

// BulletState represents an active projectile in flight within the arena.
type BulletState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the bullet instance.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Player identifier of the shooter who fired this projectile.
	OwnerId string `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// Current authoritative X position coordinate in arena pixels.
	X float32 `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	// Current authoritative Y position coordinate in arena pixels.
	Y float32 `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	// Velocity along the X axis in pixels per second.
	Vx float32 `protobuf:"fixed32,5,opt,name=vx,proto3" json:"vx,omitempty"`
	// Velocity along the Y axis in pixels per second.
	Vy            float32 `protobuf:"fixed32,6,opt,name=vy,proto3" json:"vy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulletState) Reset() {
	*x = BulletState{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulletState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulletState) ProtoMessage() {}

func (x *BulletState) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulletState.ProtoReflect.Descriptor instead.
func (*BulletState) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *BulletState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BulletState) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *BulletState) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BulletState) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BulletState) GetVx() float32 {
	if x != nil {
		return x.Vx
	}
	return 0
}

func (x *BulletState) GetVy() float32 {
	if x != nil {
		return x.Vy
	}
	return 0
}

// Snapshot carries the authoritative game state at a specific server tick.
// Broadcast to connected clients at the server tick rate (e.g. 64 Hz).
type Snapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonically increasing server tick counter at the time of snapshot capture.
	ServerTick int64 `protobuf:"varint,1,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	// Highest UserCmd sequence number from the receiving player that has been processed.
	AckSeq int32 `protobuf:"varint,2,opt,name=ack_seq,json=ackSeq,proto3" json:"ack_seq,omitempty"`
	// Complete list of active player entities in the arena during this tick.
	Entities []*EntityState `protobuf:"bytes,3,rep,name=entities,proto3" json:"entities,omitempty"`
	// Complete list of active bullets traveling through the arena during this tick.
	Bullets       []*BulletState `protobuf:"bytes,4,rep,name=bullets,proto3" json:"bullets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *Snapshot) GetServerTick() int64 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

func (x *Snapshot) GetAckSeq() int32 {
	if x != nil {
		return x.AckSeq
	}
	return 0
}

func (x *Snapshot) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *Snapshot) GetBullets() []*BulletState {
	if x != nil {
		return x.Bullets
	}
	return nil
}

// ClientMessage is the top-level envelope for all client-to-server messages over the gRPC stream.
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_JoinRequest
	//	*ClientMessage_UserCmd
	//	*ClientMessage_LeaveRequest
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetJoinRequest() *JoinRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_JoinRequest); ok {
			return x.JoinRequest
		}
	}
	return nil
}

func (x *ClientMessage) GetUserCmd() *UserCmd {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_UserCmd); ok {
			return x.UserCmd
		}
	}
	return nil
}

func (x *ClientMessage) GetLeaveRequest() *LeaveRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_LeaveRequest); ok {
			return x.LeaveRequest
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_JoinRequest struct {
	// Initial join request to enter the match.
	JoinRequest *JoinRequest `protobuf:"bytes,1,opt,name=join_request,json=joinRequest,proto3,oneof"`
}

type ClientMessage_UserCmd struct {
	// Periodic input command containing movement, aim, and weapon actions.
	UserCmd *UserCmd `protobuf:"bytes,2,opt,name=user_cmd,json=userCmd,proto3,oneof"`
}

type ClientMessage_LeaveRequest struct {
	// Graceful disconnect request.
	LeaveRequest *LeaveRequest `protobuf:"bytes,3,opt,name=leave_request,json=leaveRequest,proto3,oneof"`
}

func (*ClientMessage_JoinRequest) isClientMessage_Payload() {}

func (*ClientMessage_UserCmd) isClientMessage_Payload() {}

func (*ClientMessage_LeaveRequest) isClientMessage_Payload() {}

// ServerMessage is the top-level envelope for all server-to-client messages over the gRPC stream.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_JoinResponse
	//	*ServerMessage_Snapshot
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetJoinResponse() *JoinResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_JoinResponse); ok {
			return x.JoinResponse
		}
	}
	return nil
}

func (x *ServerMessage) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_JoinResponse struct {
	// Initial spawn confirmation and initial coordinates.
	JoinResponse *JoinResponse `protobuf:"bytes,1,opt,name=join_response,json=joinResponse,proto3,oneof"`
}

type ServerMessage_Snapshot struct {
	// Periodic authoritative world snapshot for rendering and reconciliation.
	Snapshot *Snapshot `protobuf:"bytes,2,opt,name=snapshot,proto3,oneof"`
}

func (*ServerMessage_JoinResponse) isServerMessage_Payload() {}

func (*ServerMessage_Snapshot) isServerMessage_Payload() {}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x04game\">\n" +
	"\vJoinRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xa7\x01\n" +
	"\aUserCmd\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x05R\x03seq\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x0e\n" +
	"\x02dx\x18\x04 \x01(\x02R\x02dx\x12\x0e\n" +
	"\x02dy\x18\x05 \x01(\x02R\x02dy\x12\x1b\n" +
	"\taim_angle\x18\x06 \x01(\x02R\baimAngle\x12\x12\n" +
	"\x04fire\x18\a \x01(\bR\x04fire\"+\n" +
	"\fLeaveRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"P\n" +
	"\fJoinResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x17\n" +
	"\aspawn_x\x18\x02 \x01(\x02R\x06spawnX\x12\x17\n" +
	"\aspawn_y\x18\x03 \x01(\x02R\x06spawnY\"\x80\x01\n" +
	"\vEntityState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\x14\n" +
	"\x05angle\x18\x04 \x01(\x02R\x05angle\x12\x16\n" +
	"\x06health\x18\x05 \x01(\x05R\x06health\x12\x17\n" +
	"\ais_self\x18\x06 \x01(\bR\x06isSelf\"t\n" +
	"\vBulletState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\f\n" +
	"\x01x\x18\x03 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x02R\x01y\x12\x0e\n" +
	"\x02vx\x18\x05 \x01(\x02R\x02vx\x12\x0e\n" +
	"\x02vy\x18\x06 \x01(\x02R\x02vy\"\xa0\x01\n" +
	"\bSnapshot\x12\x1f\n" +
	"\vserver_tick\x18\x01 \x01(\x03R\n" +
	"serverTick\x12\x17\n" +
	"\aack_seq\x18\x02 \x01(\x05R\x06ackSeq\x12-\n" +
	"\bentities\x18\x03 \x03(\v2\x11.game.EntityStateR\bentities\x12+\n" +
	"\abullets\x18\x04 \x03(\v2\x11.game.BulletStateR\abullets\"\xb9\x01\n" +
	"\rClientMessage\x126\n" +
	"\fjoin_request\x18\x01 \x01(\v2\x11.game.JoinRequestH\x00R\vjoinRequest\x12*\n" +
	"\buser_cmd\x18\x02 \x01(\v2\r.game.UserCmdH\x00R\auserCmd\x129\n" +
	"\rleave_request\x18\x03 \x01(\v2\x12.game.LeaveRequestH\x00R\fleaveRequestB\t\n" +
	"\apayload\"\x83\x01\n" +
	"\rServerMessage\x129\n" +
	"\rjoin_response\x18\x01 \x01(\v2\x12.game.JoinResponseH\x00R\fjoinResponse\x12,\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x0e.game.SnapshotH\x00R\bsnapshotB\t\n" +
	"\apayload2C\n" +
	"\vGameService\x124\n" +
	"\x04Play\x12\x13.game.ClientMessage\x1a\x13.game.ServerMessage(\x010\x01B/\n" +
	"\x19com.netcode.gateway.protoP\x01Z\x10service/proto/pbb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_game_proto_goTypes = []any{
	(*JoinRequest)(nil),   // 0: game.JoinRequest
	(*UserCmd)(nil),       // 1: game.UserCmd
	(*LeaveRequest)(nil),  // 2: game.LeaveRequest
	(*JoinResponse)(nil),  // 3: game.JoinResponse
	(*EntityState)(nil),   // 4: game.EntityState
	(*BulletState)(nil),   // 5: game.BulletState
	(*Snapshot)(nil),      // 6: game.Snapshot
	(*ClientMessage)(nil), // 7: game.ClientMessage
	(*ServerMessage)(nil), // 8: game.ServerMessage
}
var file_game_proto_depIdxs = []int32{
	4, // 0: game.Snapshot.entities:type_name -> game.EntityState
	5, // 1: game.Snapshot.bullets:type_name -> game.BulletState
	0, // 2: game.ClientMessage.join_request:type_name -> game.JoinRequest
	1, // 3: game.ClientMessage.user_cmd:type_name -> game.UserCmd
	2, // 4: game.ClientMessage.leave_request:type_name -> game.LeaveRequest
	3, // 5: game.ServerMessage.join_response:type_name -> game.JoinResponse
	6, // 6: game.ServerMessage.snapshot:type_name -> game.Snapshot
	7, // 7: game.GameService.Play:input_type -> game.ClientMessage
	8, // 8: game.GameService.Play:output_type -> game.ServerMessage
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	file_game_proto_msgTypes[7].OneofWrappers = []any{
		(*ClientMessage_JoinRequest)(nil),
		(*ClientMessage_UserCmd)(nil),
		(*ClientMessage_LeaveRequest)(nil),
	}
	file_game_proto_msgTypes[8].OneofWrappers = []any{
		(*ServerMessage_JoinResponse)(nil),
		(*ServerMessage_Snapshot)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
