// Package world defines the core simulation models, state representations,
// and state management operations for the game server.
package world

import (
	"log"
	"math/rand"
	"sync"
	"time"

	"github.com/server-tick-netcode/service/proto/pb"
)

const (
	// ArenaW is the arena width in pixels used for player spawn bounds.
	ArenaW = 1200.0

	// ArenaH is the arena height in pixels used for player spawn bounds.
	ArenaH = 800.0

	// DefaultSpeed is the base player movement speed in pixels per second.
	DefaultSpeed = 200.0

	// InitialHealth is the starting hit point pool for freshly spawned players.
	InitialHealth = 100

	// CmdQueueCapacity is the buffer capacity for incoming client UserCmds per player.
	CmdQueueCapacity = 128
)

// UserCmd represents a single client input command packet received over the network.
type UserCmd struct {
	// Seq is the monotonic sequence number generated by the client for prediction reconciliation.
	Seq uint32
	// DX is the normalized horizontal movement direction (-1, 0, 1).
	DX float64
	// DY is the normalized vertical movement direction (-1, 0, 1).
	DY float64
	// AimAngle is the player's aiming orientation in radians.
	AimAngle float64
	// Fire indicates whether the primary weapon trigger is depressed.
	Fire bool
}

// PlayerQueue wraps a buffered channel holding incoming UserCmds for a single player.
type PlayerQueue struct {
	// Cmds is the buffered channel holding up to CmdQueueCapacity client commands.
	Cmds chan UserCmd
}

// NewPlayerQueue allocates a new PlayerQueue with a buffer of CmdQueueCapacity.
func NewPlayerQueue() *PlayerQueue {
	return &PlayerQueue{
		Cmds: make(chan UserCmd, CmdQueueCapacity),
	}
}

// PlayerState holds the authoritative server-side state for one connected player.
// All fields are written under the WorldState mutex lock.
type PlayerState struct {
	// ID is the unique player identifier assigned when the player joins the session.
	ID string
	// X is the horizontal position in pixels within the arena.
	X float64
	// Y is the vertical position in pixels within the arena.
	Y float64
	// Angle is the aim direction in radians (0 = right, counter-clockwise positive).
	Angle float64
	// Health represents the current hit points (0-100). Elimination occurs at 0.
	Health int
	// Speed is the movement speed in pixels per second.
	Speed float64
	// LastFireTick is the server tick timestamp when the player last fired their weapon.
	LastFireTick int64
}

// BulletState represents an active projectile in flight within the arena.
type BulletState struct {
	// ID is the unique identifier for this bullet.
	ID string
	// OwnerID is the player ID of the shooter who fired this bullet.
	OwnerID string
	// X is the current horizontal position in pixels.
	X float64
	// Y is the current vertical position in pixels.
	Y float64
	// VX is the horizontal velocity component in pixels per second.
	VX float64
	// VY is the vertical velocity component in pixels per second.
	VY float64
	// BornTick is the server tick timestamp when the bullet was spawned.
	BornTick int64
}

// WorldState maintains the authoritative collection of all active entities and the simulation clock.
// Concurrent access is guarded by an embedded sync.RWMutex.
type WorldState struct {
	// Mu guards concurrent reads and writes to the world state.
	Mu sync.RWMutex
	// Tick is the monotonic simulation tick counter.
	Tick int64
	// Players maps player IDs to their respective player states.
	Players map[string]*PlayerState
	// Bullets is the list of currently active bullets simulated in the arena.
	Bullets []*BulletState
	// Queues holds the command input queues for each connected player.
	Queues map[string]*PlayerQueue
	// LastAckSeq maps each player ID to the highest UserCmd sequence number applied.
	LastAckSeq map[string]uint32
	// SnapChs holds the snapshot output channels for each connected player session.
	SnapChs map[string]chan *pb.ServerMessage
	// History retains the circular history ring buffer of past player states for lag compensation.
	History *HistoryBuffer
}

// NewWorldState creates and initializes a fresh WorldState instance with empty entity collections.
func NewWorldState() *WorldState {
	return &WorldState{
		Players:    make(map[string]*PlayerState),
		Bullets:    make([]*BulletState, 0),
		Queues:     make(map[string]*PlayerQueue),
		LastAckSeq: make(map[string]uint32),
		SnapChs:    make(map[string]chan *pb.ServerMessage),
		History:    NewHistoryBuffer(),
	}
}

// RecordHistory captures a deep-copied snapshot of current player positions into the lag compensation history buffer.
// This method is thread-safe and acquires a read lock on the world state.
func (w *WorldState) RecordHistory() {
	w.Mu.RLock()
	defer w.Mu.RUnlock()
	w.History.Record(w.Tick, w.Players)
}

// AddPlayer spawns a new player with InitialHealth in the inner 80% area of the arena.
// If the player already exists, their state and queue are re-initialized.
// This method is thread-safe and acquires a write lock.
func (w *WorldState) AddPlayer(id string) *PlayerState {
	w.Mu.Lock()
	defer w.Mu.Unlock()

	// Spawn within inner 80% of arena (10% padding on each edge: [0.10, 0.90])
	minX := ArenaW * 0.10
	maxX := ArenaW * 0.90
	minY := ArenaH * 0.10
	maxY := ArenaH * 0.90

	spawnX := minX + rand.Float64()*(maxX-minX)
	spawnY := minY + rand.Float64()*(maxY-minY)

	player := &PlayerState{
		ID:     id,
		X:      spawnX,
		Y:      spawnY,
		Angle:  0.0,
		Health: InitialHealth,
		Speed:  DefaultSpeed,
	}

	w.Players[id] = player
	w.Queues[id] = NewPlayerQueue()
	w.LastAckSeq[id] = 0

	return player
}

// RegisterSnapshotCh registers a snapshot broadcast channel for the specified player ID.
// This method is thread-safe and acquires a write lock.
func (w *WorldState) RegisterSnapshotCh(id string, ch chan *pb.ServerMessage) {
	w.Mu.Lock()
	defer w.Mu.Unlock()
	w.SnapChs[id] = ch
}

// UnregisterSnapshotCh removes and returns the snapshot channel for the specified player ID.
// This method is thread-safe and acquires a write lock.
func (w *WorldState) UnregisterSnapshotCh(id string) chan *pb.ServerMessage {
	w.Mu.Lock()
	defer w.Mu.Unlock()
	ch := w.SnapChs[id]
	delete(w.SnapChs, id)
	return ch
}

// RemovePlayer eliminates a player from the world and removes all bullets owned by them.
// This method is thread-safe and acquires a write lock.
func (w *WorldState) RemovePlayer(id string) {
	w.Mu.Lock()
	defer w.Mu.Unlock()

	delete(w.Players, id)
	delete(w.Queues, id)
	delete(w.LastAckSeq, id)
	delete(w.SnapChs, id)

	// Filter out all bullets fired by the removed player
	retainedBullets := make([]*BulletState, 0, len(w.Bullets))
	for _, b := range w.Bullets {
		if b.OwnerID != id {
			retainedBullets = append(retainedBullets, b)
		}
	}
	w.Bullets = retainedBullets
}

// EnqueueCmd pushes an incoming UserCmd into the player's queue.
// If the queue is full, the oldest command is dropped to prioritize recent input.
// Returns false if the player does not exist.
func (w *WorldState) EnqueueCmd(playerID string, cmd UserCmd) bool {
	w.Mu.RLock()
	queue, exists := w.Queues[playerID]
	w.Mu.RUnlock()

	if !exists {
		return false
	}

	select {
	case queue.Cmds <- cmd:
		return true
	default:
		// Queue full: discard oldest command and push newest
		select {
		case <-queue.Cmds:
		default:
		}
		select {
		case queue.Cmds <- cmd:
			return true
		default:
			return false
		}
	}
}

// RespawnPlayer restores an eliminated player with InitialHealth at a random inner-80% arena coordinate.
// If the player's connection session was removed in the interim, respawn is aborted.
// This method is thread-safe and acquires a write lock.
func (w *WorldState) RespawnPlayer(id string) *PlayerState {
	w.Mu.Lock()
	defer w.Mu.Unlock()

	// If player was completely unregistered (disconnected), do not respawn
	if _, registered := w.Queues[id]; !registered {
		return nil
	}

	minX := ArenaW * 0.10
	maxX := ArenaW * 0.90
	minY := ArenaH * 0.10
	maxY := ArenaH * 0.90

	spawnX := minX + rand.Float64()*(maxX-minX)
	spawnY := minY + rand.Float64()*(maxY-minY)

	player := &PlayerState{
		ID:           id,
		X:            spawnX,
		Y:            spawnY,
		Angle:        0.0,
		Health:       InitialHealth,
		Speed:        DefaultSpeed,
		LastFireTick: 0,
	}

	w.Players[id] = player
	log.Printf("[respawn] player %s respawned at (%.2f, %.2f)\n", id, spawnX, spawnY)
	return player
}

// ApplyDamageUnlocked applies damage hit points to a target player assuming the caller holds w.Mu.
// Returns the target's remaining health and a boolean indicating whether elimination occurred.
func (w *WorldState) ApplyDamageUnlocked(shooterID, targetID string, damage int, respawnDelay time.Duration) (int, bool) {
	target, exists := w.Players[targetID]
	if !exists || target.Health <= 0 {
		return 0, false
	}

	target.Health -= damage
	if target.Health < 0 {
		target.Health = 0
	}

	remainingHealth := target.Health
	log.Printf("[hit] %s -> %s (health: %d)\n", shooterID, targetID, remainingHealth)

	if remainingHealth == 0 {
		log.Printf("[elimination] player %s eliminated by %s\n", targetID, shooterID)
		// Retain player in w.Players with Health = 0 so all clients receive elimination status in snapshots
		if respawnDelay > 0 {
			time.AfterFunc(respawnDelay, func() {
				w.RespawnPlayer(targetID)
			})
		}
		return 0, true
	}

	return remainingHealth, false
}

// ApplyDamage deducts damage hit points from target player, enforces a 0 HP floor,
// and schedules an automatic respawn if the player is eliminated (health reaches 0).
// Returns the target's remaining health and a boolean indicating whether elimination occurred.
// This method is thread-safe and acquires a write lock.
func (w *WorldState) ApplyDamage(shooterID, targetID string, damage int, respawnDelay time.Duration) (int, bool) {
	w.Mu.Lock()
	defer w.Mu.Unlock()
	return w.ApplyDamageUnlocked(shooterID, targetID, damage, respawnDelay)
}
